version: '3.5'

name: niceyazilim

networks:
  app:
    driver: bridge

services:
  redis-nice:
    container_name: redis-nice
    hostname: redis-nice
    image: 'redis'
    command: redis-server --save 20 1 --loglevel warning --requirepass password123
    ports:
      - '6379:6379'
    volumes:
      - './data/redis_data:/data'
    networks:
      app:
        aliases:
          - redis-nice

  nginx-nice:
    image: nginx:latest
    container_name: nginx-nice
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nice
    networks:
      - app

  nice:
    build:
      context: ../
      dockerfile: DockerfileLocal
    container_name: nice
    hostname: nice
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=laravel.test"
      XDEBUG_CONFIG: "idekey=PHPSTORM"
    volumes:
      - ../:/var/www/
    networks:
      - app


  mysql-nice:
    container_name: mysql-nice
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      app:
        aliases:
          - mysql-nice


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-nice
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-nice
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_ARBITRARY: 1
    depends_on:
      - mysql-nice
    networks:
      - app


